{
 "title": "Kafka",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "phase",
    "query": "label_values(jvm_classes_loaded_classes, phase)"
   },
   {
    "name": "application",
    "query": "label_values(jvm_classes_loaded_classes{phase=\"$phase\"}, application)"
   },
   {
    "name": "instance",
    "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Lag Max Record",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_lag_max_records{instance=~\"$instance\"}"
    },
    {
     "expr": "kafka_consumer_records_lag_records{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Consume byte rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_consumer_bytes_consumed_total_bytes_total{instance=~\"$instance\", application=\"$application\"}[5m])"
    }
   ]
  },
  {
   "title": "Lead min record",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_lead_min_records{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Commit rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_commit_rate_commits{instance=~\"$instance\", application=\"$application\"}"
    },
    {}
   ]
  },
  {
   "title": "Partition count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_consumer_assigned_partitions{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Lead record",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_lead_records{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_join_rate_joins{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_connection_count_connections{instance=~\"$instance\"}"
    }
   ]
  }
 ]
}